name: Build
permissions:
  contents: read

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v5

      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build and Test coverage Report
        run: bash ./gradlew test unitTestCoverageReport --stacktrace

      - uses: codecov/codecov-action@v5.5.1
        with:
          files: ./app/build/reports/jacoco/unitTestCoverageReport/unitTestCoverageReport.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  apk:
    name: Generate APKs
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - uses: actions/checkout@v5
      - name: set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build debug OSS APK
        run: bash ./gradlew assembleOssDebug --stacktrace
      - name: Upload OSS APK
        uses: actions/upload-artifact@v4
        with:
          name: app-oss-debug.apk
          path: ./app/build/outputs/apk/oss/debug/app-oss-debug.apk

      - name: Build debug Playstore APK
        run: bash ./gradlew assemblePlaystoreDebug --stacktrace
      - name: Upload Playstore APK
        uses: actions/upload-artifact@v4
        with:
          name: app-playstore-debug.apk
          path: ./app/build/outputs/apk/playstore/debug/app-playstore-debug.apk

      - name: 🛡 VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          request_rate: 4
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: ./app/build/outputs/apk/oss/debug/app-oss-debug.apk